version: '2'
services:
    nginx:
        image: kang/openresty:0.1
        build: ./nginx/.
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ./nginx/conf.d:/usr/local/openresty/nginx/conf/conf.d
            - ./nginx/lua:/usr/local/openresty/nginx/lua
            - ./site:/usr/share/nginx/html
        networks:
            - frontend
        depends_on:
            - php
    php:
        image: dockerlnmp_php:latest
        build: ./php/.
        volumes:
            - ./php/php.conf:/usr/local/etc/php/conf.d/php.conf
            - ./site:/usr/share/nginx/html
        networks:
            - frontend
            - backend
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        networks:
            - backend
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis/data:/data
        networks:
            - backend
volumes:
    mysql-data: {}

networks:
    frontend:
    backend:
